### ISSUE TITLE
generate Postman collection file (or make sure the swagger is loadable)

### ISSUE THREAD

**Issue by nkuehn** [commercetools/commercetools-api-reference#12]
Postman is clearly becoming the standard "API UI" for devs, nearly all of the external devs working on commercetools are using it. 

It would be a good service providing them a readily configured postman collection to use as a starting point for their project specific test calls. 

technically postman can load swagger but 

I've created a branch here with a first run of a generator ("postman-collection-generator")  .  It does not yet provide real value and has issues but it looks all solvable and generating feels better to me than manual maintenance. 

@ValeSauer do you want to take a look and try what you can to improve the script?  Should not be too hard to do some postprocessing on the postman collection JSON before saving it. 

FYI @jayS-de

**Comment by katmatt** [comment]
We now have our custom RAML to Postman converter, which is running on our build server on each commit and pushes updated postman files to the `postman` folder of this repository. And @ValeSauer and @czacherl will update our api specification with more examples. 

@nkuehn I would suggest to close this issue and may be we can delete the corresponding branch too?

**Comment by hajoeichler** [comment]
:1st_place_medal: for @jayS-de!

**Comment by nkuehn** [comment]
yeah!  this is really cool.  
Please just delete my branch yourself,  it does neither contain significant know-how nor working code.
