### ISSUE TITLE
 markMatchingVariants is missing from query args type definition

### ISSUE THREAD

**Issue by acbeni** [commercetools/commercetools-api-reference#127]
The type definitions for product projection search is missing the query parameter markMatchingVariants. See https://docs.commercetools.com/http-api-projects-products-search#matchingVariant.

Credits to @lenkan for reporting the issue @ https://github.com/commercetools/nodejs/issues/1470

**Comment by lenkan** [comment]
Thanks for opening this issue here @acbeni. I can see that this is already reported in #22, but that issue is quite old. Are there any plans to take action on this?

**Comment by acbeni** [comment]
I will try to fix it this week for the missing matchingVariant,
