### ISSUE TITLE
One Source of truth for RAML Specs

### ISSUE THREAD

**Issue by ashishhk** [commercetools/commercetools-api-reference#195]
RAML Specs are the future single source for SDK generation, in order to have the smooth and automated process for SDK generation now and in the future, we should have API Specs(RAML) as the center of all backend team and a clear contribution guideline.

- [ ] Any external team(e..g Docs Team) should be refering to API-reference repostary as the primary source for any RAML references.

- [x] BMU Team is in synch with us and have their API specs somehow with our repository.

**Comment by jenschude** [comment]
For now the different specs are in the api-specs folder and SDKs are build from there. They may be moved to another repository later, but have to be synched to this folder for SDK generation
