### ISSUE TITLE
Azure OpenAPI specification import parsing errors

### ISSUE THREAD

**Issue by nspeet** [commercetools/commercetools-api-reference#198]
The updates to the swagger doc pass swagger 3.0 validation. However, on import into Azure parsing errors are seen.

Parsing error(s): Data and type mismatch found. [#/paths/~1[{projectKey}~1cart-discounts/post/responses/201/content/application~1json/example] Data and type mismatch found.
![AzureSwaggerImport](https://user-images.githubusercontent.com/46457269/99558426-b8103a00-2991-11eb-8a31-6afaefc99317.jpg)

"One or more fields contain incorrect values:
Parsing error(s): Schema Message must contain property specified in the discriminator type in the required field list. [#/components/schemas/Message/discriminator] Schema ResourceIdentifier must contain property specified in the discriminator typeId in the required field list. [#/components/schemas/ResourceIdentifier/discriminator] Schema TypedMoneyDraft must contain property specified in the discriminator type in the required field list. [#/components/schemas/TypedMoneyDraft/discriminator]
Parsing error(s): The input OpenAPI file is not valid for the OpenAPI specification https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md (schema https://github.com/OAI/OpenAPI-Specification/blob/master/schemas/v3.0/schema.yaml). "

Here is the fix: 
"Fix: The Commerce tools swagger schemas("Message", "TypedMoneyDraft", "ResourceIdentifier”) was missing the this block ‘required": ["type"]’. Once added the schema errors were fixed."
Please add to schema.

**Comment by nspeet** [comment]
Related: https://github.com/Azure/api-management-developer-portal/issues/294

**Comment by nspeet** [comment]
Looks like we are down to the following errors in Azure import:

"One or more fields contain incorrect values:
Parsing error(s): Schema Message must contain property specified in the discriminator type in the required field list. [#/components/schemas/Message/discriminator] Schema ResourceIdentifier must contain property specified in the discriminator typeId in the required field list. [#/components/schemas/ResourceIdentifier/discriminator] Schema TypedMoneyDraft must contain property specified in the discriminator type in the required field list. [#/components/schemas/TypedMoneyDraft/discriminator]
	Parsing error(s): The input OpenAPI file is not valid for the OpenAPI specification https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md (schema https://github.com/OAI/OpenAPI-Specification/blob/master/schemas/v3.0/schema.yaml). "

**Comment by nspeet** [comment]
Tiffany said they worked with Microsoft and made the following change to fix the issues:

"Fix: The Commerce tools swagger schemas("Message", "TypedMoneyDraft", "ResourceIdentifier”) was missing the this block ‘required": ["type"]’. Once added the schema errors were fixed."

Can this fix be added to our existing repo to fix the issue and maintain parity with Tiffany's file?

**Comment by jenschude** [comment]
We created a new generator for the OAS file which can be found in the oas folder. A follow up will be to add also the type definitions. But this solves for now the issue described here.
