### ISSUE TITLE
CustomLineItemDraft.custom should be of type CustomFieldsDraft

### ISSUE THREAD

**Issue by mvantellingen** [commercetools/commercetools-api-reference#202]
See:
- https://github.com/commercetools/commercetools-api-reference/blob/9b5f99017afa0bea3a5e85627b672d040973c596/types/cart/CustomLineItemDraft.raml#L32
- https://docs.commercetools.com/api/projects/carts#customlineitemdraft

**Comment by ashishhk** [comment]
The changes are merged to master, hereby closing this issue, please let us know if there are any further comments.
