### ISSUE TITLE
DeliveryItem quantity type wrong

### ISSUE THREAD

**Issue by barbara79** [commercetools/commercetools-api-reference#235]
DeliveryItem quantity should be of type number and format int64

**Comment by ashishhk** [comment]
Please note the changes have been released in Java SDK in 3.0.1 version 
https://github.com/commercetools/commercetools-sdk-java-v2/releases/tag/3.0.1

And should also be release to other SDKs in their next versions wherever relavent.

**Comment by jenschude** [comment]
it mainly affected java. Typescript only knows numbers. PHP has scalars and dotnet is not stable released ;)
