### ISSUE TITLE
key in cart is not optional

### ISSUE THREAD

**Issue by mht-dotsource** [commercetools/commercetools-api-reference#239]
While using the typescript platform-sdk (i.e. https://github.com/commercetools/commercetools-sdk-typescript/tree/master/packages/platform-sdk/src/generated) we saw a breaking change in our code while updating the minor version of the dependencies. After digging into the issue we found that the property **key** is not marked as optional.

https://github.com/commercetools/commercetools-api-reference/blob/254b925ec5c3822d6b7e55c19c40a6918181d208/api-specs/api/types/cart/Cart.raml#L13

Yet key is optional for carts https://docs.commercetools.com/api/projects/carts#cart

Can you please have a look into that. ty.

**Comment by jenschude** [comment]
Has been fixed and a new typescript SDK (1.9.0) has been released.

Thanks for the report
