### ISSUE TITLE
Wrong case in uriParameterName

### ISSUE THREAD

**Issue by Multiply** [commercetools/commercetools-api-reference#249]
I'm currently trying to generate a new go sdk using labd's project, and I've encountered an issue with state deletes, not generated correctly, due to casing issue, meaning it doesn't correctly replace certain values in the URL.

I can fix it in the generator of course, but would prefer to have a proper root fix implemented where the problem is caused in the first place.

It seems that there's a casing issue in the following file:
https://github.com/commercetools/commercetools-api-reference/blob/dfbd56a8b3921f1fb7a09aefb297ec650781b06e/api-specs/api/resources/states.raml#L45-L49

The path says `key`, but the `uriParameterName` says `Key`, which seems incorrect.

Is this the right place to report the issue, and can I do something to help fix it? (I'm guessing it's generated code)

**Comment by jenschude** [comment]
Oh yeah that's true. Will fix it in the internal repo.

Nevertheless it makes sense to make the generator a little bit fault tolerant. For the PHP generator we didn't relied on the uriParameters but directly used the variable from the UriTemplates.

See 

https://github.com/commercetools/rmf-codegen/blob/main/languages/php/src/main/kotlin/io/vrap/codegen/languages/php/AbstractRequestBuilder.kt#L49

and

https://github.com/commercetools/rmf-codegen/blob/main/languages/php/src/main/kotlin/io/vrap/codegen/languages/php/extensions/VrapExtensions.kt#L244-L246

**Comment by jenschude** [comment]
Ah yeah while re-reading your comment i saw my mistake. :)

So I would suggest you to go on to checkout the repo and fix this typo. Btw the labd generator is maybe getting incorporated in our own code gen. Please see here https://github.com/commercetools/rmf-codegen/pull/219

**Comment by Multiply** [comment]
Awesome. I'll follow along in there.

Are you also planning on taking over on the terraform provider?

**Comment by jenschude** [comment]
Depends on the time of our friends at lab digital. But yeah it would be a nice addition

**Comment by jenschude** [comment]
The uriParameter has been fixed now in the specs

Thanks for the report
