### ISSUE TITLE
Wrong type for shipping-method's localized_description update action

### ISSUE THREAD

**Issue by Multiply** [commercetools/commercetools-api-reference#250]
Checking the docs here: https://docs.commercetools.com/api/projects/shippingMethods#set-localized-description
I'm assuming the value here should be `LocalizedString` and not `string`:
https://github.com/commercetools/commercetools-api-reference/blob/1e2ddc7d5d9726800779ce1d28dfeaed847ae85f/api-specs/api/types/shipping-method/updates/ShippingMethodSetLocalizedDescriptionAction.raml#L10

**Comment by jenschude** [comment]
Should be fixed now with 0207c8a

thx for the report
