### ISSUE TITLE
[graphQL] missing customerEmail in orders and carts

### ISSUE THREAD

**Issue by tsmiatacz-engi** [commercetools/commercetools-api-reference#254]
First of all, sorry if this is a wrong repo to raise this issue. Please point me to the appropriate place if this is the case.

There's this inconsistency in your gQL API where querying for `customerEmail` will always return `null` even if there is an associated customer, eg.
```
query  {
  orders {
    results {
      customerEmail
      customer {
        email
      }
    }
  }
}
```
in my project will return
```
{
  "data": {
    "orders": {
      "results": [
        {
          "customerEmail": null,
          "customer": {
            "email": "bar.pek@bar.pek"
          }
        },
        ...
      ]
    }
  }
}
```
Same goes for carts query.

Using `customer.email` instead solves my problem only partially because I can't sort over this field.

**Comment by jenschude** [comment]
Hi,

you should contact our support using the [support portal](https://support.commercetools.com) or our support@commercetools.com email.
