### ISSUE TITLE
No RAML definition for "changeShoppingListsConfiguration" project update action

### ISSUE THREAD

**Issue by kirmerzlikin** [commercetools/commercetools-api-reference#257]
Currently there is no corresponding RAML definition for [_"changeShoppingListsConfiguration"_](https://docs.commercetools.com/api/projects/project#change-shoppinglists-configuration) project update action.  

This leads to Java SDK v2 lacking a model for this update action, which makes SDK incomplete and unsuitable for a valid use case. (see commercetools/commercetools-sdk-java-v2#167)

**Comment by jenschude** [comment]
Fixed with 54444c4
