### ISSUE TITLE
Can I change the store of a Cart type?

### ISSUE THREAD

**Issue by PauloPortugal** [commercetools/commercetools-api-reference#260]
I cannot find an UpdateAction type that can update the `store.key` field of a `cart`.
Do I have to create a new cart every time I have to update a store for that given cart?

What is the reason behind it?

This is more of a question, apologies if this is not the correct method to ask questions.
Thank you in advance.

**Comment by jenschude** [comment]
As the docs state (https://docs.commercetools.com/api/projects/carts#cartdraft).

'Assigns the new cart to the store. The store assignment can not be modified.'

Btw this is the api specification. In case you need further informations please contact our [support](http://support.commercetools.com)
