### ISSUE TITLE
Invalid package names for 5 business unit types

### ISSUE THREAD

**Issue by mvantellingen** [commercetools/commercetools-api-reference#273]
While regenerating the Python SDK we came into an issue where a cyclic import order was introduced. The cause seems to be the following 5 types which are defined with the package `BusinessUnit` instead of the `Me` package used for all other `My*` actions.

- `MyBusinessUnitChangeAssociateAction`
- `MyBusinessUnitChangeNameAction`
- `MyBusinessUnitChangeParentUnitAction`
- `MyBusinessUnitSetDefaultBillingAddressAction`
- `MyBusinessUnitSetDefaultShippingAddressAction`

**Comment by jenschude** [comment]
Fixed with 7e260e1
