### ISSUE TITLE
(low): api-specs "API Design Guidline" link is invalid

### ISSUE THREAD

**Issue by osxhacker** [commercetools/commercetools-api-reference#280]
In the [api-specs readme.md](https://github.com/commercetools/commercetools-api-reference/blob/main/api-specs/readme.md), the "API Design Guidline" link on line 4 points to an unresolvable resource (404).

**Comment by jenschude** [comment]
It points to a private repository. We synchronize the officially released features from our internal spec repository to the api-reference. This way we can work on updating the spec while developing new features. Once it's publicly available it will be updated here automatically.
