### ISSUE TITLE
(spec): oauth.raml "securedBy" property must be a list

### ISSUE THREAD

**Issue by osxhacker** [commercetools/commercetools-api-reference#281]
As per the [RAML specification](https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md/#applying-security-schemes):

> The value assigned to the securedBy node MUST be a list of any of the security schemes previously defined in the securitySchemes node of RAML document root.

When [securedBy in oauth.raml](https://github.com/commercetools/commercetools-api-reference/blob/main/api-specs/api/oauth.raml#L13) is updated from:

```
  securedBy: basic
```

To be:

```
  securedBy: [ basic ]
```

The definition is fully conformant and immediately usable  👍 .

🏴‍☠️

**Comment by jenschude** [comment]
Oh nice catch.

Also the oauth.raml is more like a test. As typically you don't generate a oauth client. Nevertheless will update it

**Comment by osxhacker** [comment]
No worries Jens, I just was in the neighborhood and opened a ticket before I forgot again 😃 .  With this one edit, [scraml](https://github.com/commercetools/scraml) was able to generate OAuth2 compatible scaffolding a while back.

**Comment by jenschude** [comment]
It's fixed now
