### ISSUE TITLE
Missing Scalars in GraphQL SDL file

### ISSUE THREAD

**Issue by NullScope** [commercetools/commercetools-api-reference#282]
According to the [docs](https://docs.commercetools.com/api/graphql) this [file](https://github.com/commercetools/commercetools-api-reference/blob/main/api-specs/graphql/schema.sdl) should be used for development and production usage, however when we try to use `buildSchema` from `graphql` package, it errors out because it's missing both `Long` and `BigDecimal` scalars.

If we add these two scalars into the file, the schema is built successfully, an example can be found [here](https://replit.com/@NullScope/commercetools-missing-scalars#index.js) on replit (keep in mind it might take a while to load)

**Comment by jenschude** [comment]
I reported it to the respective team. For now the only workaround is as you did to extend the file with these missing types

**Comment by NullScope** [comment]
Thank you @jenschude, when this SDL file gets fixed, will we be notified in advance before it gets published here? I ask because if it gets fixed without warning while we are extending the file ourselves, it will cause the `buildSchema` to throw errors as well

**Comment by jenschude** [comment]
Once it's fixed it will be automatically updated in the main branch. If you want to prevent a failing build you could point to the permalink of the file

**Comment by NullScope** [comment]
Hi @jenschude, any updates on this issue?

**Comment by NullScope** [comment]
Hi, I can see its already been added on this [commit](https://github.com/commercetools/commercetools-api-reference/commit/b738b44e08ae31498f4a2b3d9afb01ef3d9f6df7) on June 19th, I'll close this issue now
