### ISSUE TITLE
Spelling/Case issue Destination.queueURL field

### ISSUE THREAD

**Issue by mvantellingen** [commercetools/commercetools-api-reference#32]
Hi,

There is a case mismatch for the Subscription.Destination.queueURL field. See https://github.com/commercetools/commercetools-api-reference/blob/be4efaee724385c66ab8b313c5ba4215193b44dc/types/subscription/SqsDestination.raml#L14

According to the documentation (and test against the commercetools API) it should be spelled as `queueUrl`

**Comment by jenschude** [comment]
Fixed it.

Thanks for the hint!
