### ISSUE TITLE
Price.value and PriceDraft.value types (Money vs TypedMoney)

### ISSUE THREAD

**Issue by mvantellingen** [commercetools/commercetools-api-reference#34]
Hi,

I found another issue. The `Price.value` attribute is according to the documentation of type `BaseMoney` which is a discrminator object. The raml however points to the `Money` type which has no discriminator support.

See

- https://github.com/commercetools/commercetools-api-reference/blob/5b98b89d93a96149213b435f2c6f48c3bd056fb1/types/common/Price.raml#L12
- https://github.com/commercetools/commercetools-api-reference/blob/5b98b89d93a96149213b435f2c6f48c3bd056fb1/types/common/PriceDraft.raml#L10

**Comment by jenschude** [comment]
We have been lately changing modelling of money and their drafts. They are now separated. So I will close this issue.
