### ISSUE TITLE
GeoJson.coordinates.items value not set

### ISSUE THREAD

**Issue by mvantellingen** [commercetools/commercetools-api-reference#36]
The GeoJson.coordinates attribute is an array. For code generation it would be helpful to specify the `items` and set it to `number`.

See https://github.com/commercetools/commercetools-api-reference/blob/be4efaee724385c66ab8b313c5ba4215193b44dc/types/common/GeoJson.raml#L12

**Comment by jenschude** [comment]
In the GeoJson type itself it's correct as other subtypes may have nested arrays. But for the GeoJsonPoint I added the items type
