### ISSUE TITLE
FieldDefinition.inputHint should be of type TextInputHint (?)

### ISSUE THREAD

**Issue by mvantellingen** [commercetools/commercetools-api-reference#37]
According to the documentation, the `FieldDefinition.inputHint` should either be `singleLine` or `multiLine`. I think that means the `TextInputHint` enum.

See https://github.com/commercetools/commercetools-api-reference/blob/master/types/type/FieldDefinition.raml#L18

**Comment by jenschude** [comment]
Changed it 👍
