### ISSUE TITLE
Transaction.amount vs TransactionDraft.amount (different types)

### ISSUE THREAD

**Issue by mvantellingen** [commercetools/commercetools-api-reference#62]
Not sure if this is a duplicate of #34 

The fields for `Transaction.amount` and `TransactionDraft.amount` use a different type. According to the documentation both fields should be of type `Money` but the raml uses `TypedMoney` for `Transaction.amount` and `Money` for `TransactionDraft.amount`

See https://github.com/commercetools/commercetools-api-reference/blob/master/types/payment/Transaction.raml#L16 and https://github.com/commercetools/commercetools-api-reference/blob/master/types/payment/TransactionDraft.raml#L13

**Comment by jenschude** [comment]
In this case it's correct. Cause the API will always answer with a money object with has the type field so it's a TypedMoney. The draft object can contain an untyped money object.

Besides that in the reference I had to introduce the TypedMoney to differentiate between the two possible representations the Money can have as stated in the documentation.

**Comment by mvantellingen** [comment]
Ok clear. So should the `amount` field at https://docs.commercetools.com/http-api-projects-payments#transaction be `TypedMoney` instead of `Money` then. Or is this only in the raml?

**Comment by jenschude** [comment]
The documentation does not have a differentiation between TypedMoney and Money. But semantically you are right. The API returns a Money representation which is typed.

**Comment by mvantellingen** [comment]
Ok thanks for the clarification :-)
