### ISSUE TITLE
Message Types missing attributes

### ISSUE THREAD

**Issue by davidweterings** [commercetools/commercetools-api-reference#63]
Most messages in https://docs.commercetools.com/http-api-message-types have attributes that are not defined in the raml, usually starting with 'old'

For example:
The OrderPaymentStateChanged message https://docs.commercetools.com/http-api-message-types#orderpaymentstatechanged-message should have an 'oldPaymentState' field (and the docs incorrectly state there is an 'id' field aswell.)

**Comment by jenschude** [comment]
Just added them and fixed some other minor stuff.

Thanks 👍
