### ISSUE TITLE
Don't use "pseudo-raml" files in Includes (e.g. types.raml)

### ISSUE THREAD

**Issue by nkuehn** [commercetools/commercetools-api-reference#77]
We started using the RAML spec in various tooling (loading into gatsby via the JS parser, trying to use generators that are out in the market etc) and ran into problems with the files that don't have a `#%RAML 1.0 FooType`  header but are a kind of intermediate include. 

The JS parser simply does not proceed including these into the effective AST, i.e. there are no types. 

It's an old point of discussion and I do understand the rationale of not wanting 1000+ individual import statements in the root `api.raml`, but I think if we want to drive adoption we need to provide at least optional ways to load the stuff that are robust in the marketplace of tooling. 

I have copied the `types.raml` over into the `api.raml` now to be able to proceed but it's not nice. 

Options I can imagine:
 * additionally generating a separate root `api.raml` that has more inlined so only fully specced patterns are used
 * using the library pattern (which has its own downsides again)
 * providing a generated root file that is in fact an Overlay, contains all the types and extends the api.raml that is 

My personal preference is to switch to making the various root .raml  files that we need for different use cases (e.g. also some that don't provide the full API but e.g. only the product catalog) fully generated from a template or fragment.  

FYI @davifantasia

**Comment by jenschude** [comment]
This is valid RAML and the Javascript parser is able to parse it and also give back the types. Else the build would break as I'm needing the javascript parser to validate the markdown inside the RAML files.

**Comment by nkuehn** [comment]
Yes, the spec says 
> A file to be included MAY begin with a RAML fragment identifier line [...]
So it's okay

I'm re-testing, sorry for the mess.  Now that I understand the parser much better that would have been avoidable.  Thanks for looking into it!
