### ISSUE TITLE
Add new stores fields

### ISSUE THREAD

**Issue by davidweterings** [commercetools/commercetools-api-reference#80]
Please add the new fields and types introduced by: https://docs.commercetools.com/release-notes.html#releases-2019-04-17-introducing-stores

**Comment by katmatt** [comment]
@davidweterings We now merged those changes to master and we're looking forward to your feedback.

**Comment by davidweterings** [comment]
@katmatt awesome! I've integrated it into https://github.com/labd/commercetools-python-sdk and https://github.com/labd/terraform-provider-commercetools We'll be implementing it for our environments in the next few weeks!
