### ISSUE TITLE
APIClient delete has no version

### ISSUE THREAD

**Issue by davidweterings** [commercetools/commercetools-api-reference#97]
Context:

We're generating our Go SDK from the RAML definition and noticed a few inconsistencies.
As discussed with Matthias, I'm making a separate issue for each finding.

Issue:

ApiClient type has no version (which makes sense), but the delete on most resources does require specifying a version. I'm wondering if this can somehow be communicated through the RAML definition. The alternative is that we check ourselves if the type has a 'version' attribute, so I consider this to be relatively low priority.

**Comment by jenschude** [comment]
ApiClient has no version as it can't be updated. Please also take a look at the documentation (https://docs.commercetools.com/http-api-projects-api-clients#apiclient)

Also the delete endpoint doesn't need a version as parameter (https://docs.commercetools.com/http-api-projects-api-clients#delete-an-api-client)

So I'm closing this issue as the reference reflects the API behavior
