### ISSUE TITLE
Missing traits on many resources

### ISSUE THREAD

**Issue by davidweterings** [commercetools/commercetools-api-reference#99]
Context:

We're generating our Go SDK from the RAML definition and noticed a few inconsistencies.
As discussed with Matthias, I'm making a separate issue for each finding.

Issue:
Many of the traits are applicable (f.e. `expandable`), but are not defined on any of the resources.

**Comment by jenschude** [comment]
It would be good to know at which endpoints exactly the expandable trait is missing. It should only be missing on resources of `type: base`. All other resources are inheriting the trait from the resource type `baseResource` and `baseDomain`.

Atm I would have to double check all endpoints with the documentation if they may support expansion or not.

**Comment by davidweterings** [comment]
Oh apologies, I was not aware it worked it like this! That should be enough to figure out which types are expandable and which are not.
